USE [master]
GO
/****** Object:  Database [NetBanking_Sys_WebApp]    Script Date: 12/6/2021 11:20:17 PM ******/
CREATE DATABASE [NetBanking_Sys_WebApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NetBanking_Sys_WebApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLBRYAN\MSSQL\DATA\NetBanking_Sys_WebApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NetBanking_Sys_WebApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLBRYAN\MSSQL\DATA\NetBanking_Sys_WebApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NetBanking_Sys_WebApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET ARITHABORT OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET  ENABLE_BROKER 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET  MULTI_USER 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET DB_CHAINING OFF 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET QUERY_STORE = OFF
GO
USE [NetBanking_Sys_WebApp]
GO
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[Cedula] [varchar](11) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[FechaNacimiento] [date] NOT NULL,
	[Direccion] [varchar](130) NOT NULL,
	[Telefono] [varchar](12) NOT NULL,
	[Correo_Electronico] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[Cedula] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTES_CUENTAS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES_CUENTAS](
	[Cedula] [varchar](11) NOT NULL,
	[Numero_Cuenta] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Cedula] ASC,
	[Numero_Cuenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTES_PRESTAMOS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES_PRESTAMOS](
	[Cedula] [varchar](11) NOT NULL,
	[Codigo_Prestamo] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Cedula] ASC,
	[Codigo_Prestamo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTES_TARJETAS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES_TARJETAS](
	[Cedula] [varchar](11) NOT NULL,
	[Numero_Tarjeta] [varchar](16) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Cedula] ASC,
	[Numero_Tarjeta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUENTAS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUENTAS](
	[Numero_Cuenta] [varchar](20) NOT NULL,
	[Fecha_Creacion] [date] NOT NULL,
	[Balance] [decimal](13, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Numero_Cuenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HISTORIAL_DEPOSITOS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HISTORIAL_DEPOSITOS](
	[Codigo_Deposito] [varchar](8) NOT NULL,
	[Tarjeta_Origen_Retiro] [varchar](16) NOT NULL,
	[Numero_Cuenta_Destino_Deposito] [varchar](20) NOT NULL,
	[Monto_Depositado] [decimal](13, 2) NOT NULL,
	[Fecha] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Codigo_Deposito] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HISTORIAL_PAGOS_PRESTAMOS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HISTORIAL_PAGOS_PRESTAMOS](
	[Codigo_Pago] [varchar](7) NOT NULL,
	[Codigo_Prestamo] [varchar](10) NOT NULL,
	[MontoPagado] [decimal](13, 2) NOT NULL,
	[Fecha] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Codigo_Pago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HISTORIAL_PAGOS_TARJETA]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HISTORIAL_PAGOS_TARJETA](
	[Codigo_Pago] [varchar](7) NOT NULL,
	[Numero_Tarjeta] [varchar](16) NOT NULL,
	[Numero_Cuenta_Origen] [varchar](20) NOT NULL,
	[MontoPagado] [decimal](13, 2) NOT NULL,
	[Fecha] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Codigo_Pago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HISTORIAL_RETIROS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HISTORIAL_RETIROS](
	[Codigo_Retiro] [varchar](7) NOT NULL,
	[Numero_Cuenta_Origen_Retiro] [varchar](20) NOT NULL,
	[Tarjeta_Destino_Deposito] [varchar](16) NOT NULL,
	[MontoRetirado] [decimal](13, 2) NOT NULL,
	[Fecha] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Codigo_Retiro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRESTAMOS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRESTAMOS](
	[Codigo_Prestamo] [varchar](10) NOT NULL,
	[Fecha_Inicio] [date] NOT NULL,
	[Monto_Prestado] [decimal](11, 2) NOT NULL,
	[Cuotas_Totales_A_Pagar] [int] NOT NULL,
	[CuotasPagadas] [int] NOT NULL,
	[PagoPorCuota] [decimal](11, 2) NOT NULL,
	[TasaInteres] [decimal](5, 2) NULL,
	[Activo] [varchar](2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Codigo_Prestamo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLES]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLES](
	[idRol] [int] NOT NULL,
	[nombreRol] [varchar](25) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[idRol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TARJETAS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TARJETAS](
	[Numero_Tarjeta] [varchar](16) NOT NULL,
	[Valor_De_Validacion] [int] NOT NULL,
	[Fecha_Vencimiento] [date] NOT NULL,
	[BalanceDisponible] [decimal](13, 2) NOT NULL,
	[BalanceConsumido] [decimal](13, 2) NULL,
	[Fecha_Expedicion] [date] NOT NULL,
	[TopeCredito] [decimal](13, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[Numero_Tarjeta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 12/6/2021 11:20:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[NombreUsuario] [varchar](100) NOT NULL,
	[passwordHashed] [varchar](max) NOT NULL,
	[idRol] [int] NOT NULL,
	[RutaFoto] [varchar](max) NULL,
	[Cedula] [varchar](11) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NombreUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTES_CUENTAS]  WITH CHECK ADD FOREIGN KEY([Cedula])
REFERENCES [dbo].[CLIENTES] ([Cedula])
GO
ALTER TABLE [dbo].[CLIENTES_CUENTAS]  WITH CHECK ADD FOREIGN KEY([Numero_Cuenta])
REFERENCES [dbo].[CUENTAS] ([Numero_Cuenta])
GO
ALTER TABLE [dbo].[CLIENTES_PRESTAMOS]  WITH CHECK ADD FOREIGN KEY([Cedula])
REFERENCES [dbo].[CLIENTES] ([Cedula])
GO
ALTER TABLE [dbo].[CLIENTES_PRESTAMOS]  WITH CHECK ADD FOREIGN KEY([Codigo_Prestamo])
REFERENCES [dbo].[PRESTAMOS] ([Codigo_Prestamo])
GO
ALTER TABLE [dbo].[CLIENTES_TARJETAS]  WITH CHECK ADD FOREIGN KEY([Cedula])
REFERENCES [dbo].[CLIENTES] ([Cedula])
GO
ALTER TABLE [dbo].[CLIENTES_TARJETAS]  WITH CHECK ADD FOREIGN KEY([Numero_Tarjeta])
REFERENCES [dbo].[TARJETAS] ([Numero_Tarjeta])
GO
ALTER TABLE [dbo].[HISTORIAL_DEPOSITOS]  WITH CHECK ADD FOREIGN KEY([Numero_Cuenta_Destino_Deposito])
REFERENCES [dbo].[CUENTAS] ([Numero_Cuenta])
GO
ALTER TABLE [dbo].[HISTORIAL_DEPOSITOS]  WITH CHECK ADD FOREIGN KEY([Tarjeta_Origen_Retiro])
REFERENCES [dbo].[TARJETAS] ([Numero_Tarjeta])
GO
ALTER TABLE [dbo].[HISTORIAL_PAGOS_PRESTAMOS]  WITH CHECK ADD FOREIGN KEY([Codigo_Prestamo])
REFERENCES [dbo].[PRESTAMOS] ([Codigo_Prestamo])
GO
ALTER TABLE [dbo].[HISTORIAL_PAGOS_TARJETA]  WITH CHECK ADD FOREIGN KEY([Numero_Tarjeta])
REFERENCES [dbo].[TARJETAS] ([Numero_Tarjeta])
GO
ALTER TABLE [dbo].[HISTORIAL_PAGOS_TARJETA]  WITH CHECK ADD FOREIGN KEY([Numero_Cuenta_Origen])
REFERENCES [dbo].[CUENTAS] ([Numero_Cuenta])
GO
ALTER TABLE [dbo].[HISTORIAL_RETIROS]  WITH CHECK ADD FOREIGN KEY([Numero_Cuenta_Origen_Retiro])
REFERENCES [dbo].[CUENTAS] ([Numero_Cuenta])
GO
ALTER TABLE [dbo].[HISTORIAL_RETIROS]  WITH CHECK ADD FOREIGN KEY([Tarjeta_Destino_Deposito])
REFERENCES [dbo].[TARJETAS] ([Numero_Tarjeta])
GO
ALTER TABLE [dbo].[USUARIOS]  WITH CHECK ADD FOREIGN KEY([idRol])
REFERENCES [dbo].[ROLES] ([idRol])
GO
ALTER TABLE [dbo].[CLIENTES]  WITH CHECK ADD CHECK  ((len([Cedula])>(10) AND len([Cedula])<(12)))
GO
ALTER TABLE [dbo].[CLIENTES]  WITH CHECK ADD CHECK  ((len([Telefono])>(11) AND len([Telefono])<(13)))
GO
ALTER TABLE [dbo].[CUENTAS]  WITH CHECK ADD CHECK  ((len([Numero_Cuenta])=(20)))
GO
ALTER TABLE [dbo].[HISTORIAL_DEPOSITOS]  WITH CHECK ADD CHECK  ((len([Codigo_Deposito])=(8)))
GO
ALTER TABLE [dbo].[HISTORIAL_PAGOS_PRESTAMOS]  WITH CHECK ADD CHECK  ((len([Codigo_Pago])=(7)))
GO
ALTER TABLE [dbo].[HISTORIAL_PAGOS_TARJETA]  WITH CHECK ADD CHECK  ((len([Codigo_Pago])=(7)))
GO
ALTER TABLE [dbo].[HISTORIAL_PAGOS_TARJETA]  WITH CHECK ADD CHECK  ((len([Numero_Tarjeta])=(16)))
GO
ALTER TABLE [dbo].[HISTORIAL_PAGOS_TARJETA]  WITH CHECK ADD CHECK  ((len([Numero_Cuenta_Origen])=(20)))
GO
ALTER TABLE [dbo].[HISTORIAL_RETIROS]  WITH CHECK ADD CHECK  ((len([Codigo_Retiro])=(7)))
GO
ALTER TABLE [dbo].[PRESTAMOS]  WITH CHECK ADD CHECK  (([Activo]='Si' OR [Activo]='No'))
GO
ALTER TABLE [dbo].[PRESTAMOS]  WITH CHECK ADD CHECK  ((len([Codigo_Prestamo])=(10)))
GO
ALTER TABLE [dbo].[TARJETAS]  WITH CHECK ADD CHECK  ((len([Numero_Tarjeta])=(16)))
GO
ALTER TABLE [dbo].[TARJETAS]  WITH CHECK ADD CHECK  (([Valor_De_Validacion]>=(100) AND [Valor_De_Validacion]<=(999)))
GO
USE [master]
GO
ALTER DATABASE [NetBanking_Sys_WebApp] SET  READ_WRITE 
GO
